version: "3"

services:
  db:
    image: mariadb:10.4.5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: docker
    ports:
      - "3306:3306"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    networks:
      - docker
    restart: always

  web:
    build:
      context: .
#    image: dms:0.1
    environment:
      SECRET_KEY: com.aisino.testcenter.testcenter3093
      DATABASE_URL: root:test@db:3306
      MAIL_SERVER: smtp.qiye.aliyun.com
      MAIL_USERNAME: xuhang@aisino.com
      MAIL_PASSWORD:
      ADMIN: xuhang@aisino.com
#      SESSION_TIMEOUT: 60
    volumes:
      - ./logs:/opt/app/logs
    networks:
      - docker
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.17.3-alpine
    ports:
      - "80:80"
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker

networks:
  docker:
    driver: bridge
